version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    container_name: ref-postgres15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    container_name: ref-web
    build: ../
    restart: always
    volumes:
      - static:/app/static/
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    container_name: ref-nginx
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    depends_on:
      - web

volumes:
  static:
  postgres:
